GUI_WINDOW_WIDTH = 750
GUI_WINDOW_HEIGHT = 500

MIN_SHAPE_RADIUS = 35
MAX_SHAPE_RADIUS = 50

MIN_BROADCAST_RANGE = 100
MAX_BROADCAST_RANGE = 250

MIN_CENTROID_MOVEMENT = -25
MAX_CENTROID_MOVEMENT = 25