GUI_WINDOW_TITLE = "Practical Geographic Forwarding"

GUI_WINDOW_WIDTH = 750
GUI_WINDOW_HEIGHT = 500

SHAPE_RADIUS = 25

MINIMUM_NODES_DISTANCE = SHAPE_RADIUS * 2

MIN_BROADCAST_RANGE = 50
MAX_BROADCAST_RANGE = 150

MIN_CENTROID_MOVEMENT = -10
MAX_CENTROID_MOVEMENT = 10

NUMBER_OF_NODES_TO_GENERATE = 15

# 10%
GUI_CANVAS_CROP_PERCENTAGE = 10

FONT = "Arial 10 bold"

LOCATION_AWARE_NODE_COLOR = "black"
LOCATION_IGNORANT_NODE_COLOR = "red"
WRONGLY_INITIALIZED_NODE_COLOR = "purple"

INNER_NODE_FILL_COLOR = "#fff"
OUTER_NODE_FILL_COLOR = "#ccc"

NODE_OUTLINE_DEFAULT_COLOR = "#000"
NODE_FILL_DEFAULT_COLOR = ""

NUMBER_OF_MAXIMUM_TRIALS_AT_NODE_GENERATION = 50
NUMBER_OF_MAXIMUM_MOVEMENT_TRIAL_PER_NODE = 10

# KEYS
RESTART_KEY = "<Return>"
MOVEMENT_KEY = "m"

# 70%
RATIO_OF_LOCATION_AWARE_NODES = 70