GUI_WINDOW_TITLE = "Practical Geographic Forwarding"

GUI_WINDOW_WIDTH = 1250
GUI_WINDOW_HEIGHT = 600

TEXT_ANCHOR = "nw"

HELPER_TEXT_X_DIRECTION_DISPLACEMENT = 20
HELPER_TEXT_Y_DIRECTION_DISPLACEMENT = 580

ROUTING_LOG_TEXT_X_DIRECTION_DISPLACEMENT = 230
ROUTING_LOG_TEXT_Y_DIRECTION_DISPLACEMENT = 580

NODE_SHAPE_RADIUS = 25
PACKET_SHAPE_RADIUS = 15

ROUTE_COLOR = "green"
ROUTE_BOLDNESS = 0

INF_NODE_SHAPE_RADIUS = 25
INF_NODE_BROADCAST_RANGE_RADIUS = 30
INF_NODE_COORDINATES = (
    (300, 225),
    (500, 200),
    (550, 300),
    (525, 400),
    (725, 450),
    (900, 375),
    (950, 300)
)

MINIMUM_NODES_DISTANCE = NODE_SHAPE_RADIUS * 2

MIN_BROADCAST_RANGE = 50
MAX_BROADCAST_RANGE = 150

MIN_CENTROID_MOVEMENT = -10
MAX_CENTROID_MOVEMENT = 10

NUMBER_OF_NODES_TO_GENERATE = 10

# %
GUI_CANVAS_CROP_PERCENTAGE = 20

HELPER_TEXT_FONT = "Courier 13 bold"
HELPER_TEXT_COLOR = "black"

ROUTING_LOG_TEXT_FONT = "Courier 13 bold"
ROUTING_LOG_TEXT_COLOR = "black"

SUCCESS_TEXT_COLOR = "green"
FAILURE_TEXT_COLOR = "red"

LOCATION_AWARE_NODE_COLOR = "black"
LOCATION_IGNORANT_NODE_COLOR = "red"
WRONGLY_INITIALIZED_NODE_COLOR = "purple"

NODE_IN_NETWORK_SHAPE_FILL_COLOR = "#fff"
NODE_BROADCAST_RANGE_OUTLINE_COLOR = "#ccc"
NODE_OUT_OF_NETWORK_SHAPE_FILL_COLOR = "#F0C2C4"
NODE_OUT_OF_NETWORK_BROADCAST_RANGE_OUTLINE_COLOR = "#F0C2C4"

INF_NODE_SHAPE_FILL_COLOR = "#fff"
INF_NODE_BROADCAST_RANGE_OUTLINE_COLOR = "#ccc"

NODE_OUTLINE_DEFAULT_COLOR = "#000"
NODE_FILL_DEFAULT_COLOR = ""

PACKET_OUTLINE_COLOR = "green"

NUMBER_OF_MAXIMUM_TRIALS_AT_NODE_GENERATION = 50
NUMBER_OF_MAXIMUM_MOVEMENT_TRIAL_PER_NODE = 10

# KEYS
RESTART_KEY = "<Return>"
MOVEMENT_KEY = "m"
BASIC_ROUTING_KEY = "b"
LOCATION_PROXY_ROUTING_KEY = "l"
INF_ROUTING_KEY = "r"
TURN_INTERMEDIATE_NODE_FORWARDING_ON_KEY = "i"
TURN_INTERMEDIATE_NODE_FORWARDING_OFF_KEY = "o"
TOGGLE_AUTOMATIC_SIMULATION_KEY = "a"
TOGGLE_LOGWINDOW_KEY = "q"

# KEYS display
RESTART_KEY_DISPLAY = "↲"
MOVEMENT_KEY_DISPLAY = "M"
BASIC_ROUTING_KEY_DISPLAY = "B"
LOCATION_PROXY_ROUTING_KEY_DISPLAY = "L"
INF_ROUTING_KEY_DISPLAY = "R"
TURN_INTERMEDIATE_NODE_FORWARDING_ON_KEY_DISPLAY = "I"
TURN_INTERMEDIATE_NODE_FORWARDING_OFF_KEY_DISPLAY = "O"
TOGGLE_AUTOMATIC_SIMULATION_KEY_DISPLAY = "A"

# %
RATIO_OF_LOCATION_AWARE_NODES = 60

# NODE ID CODES
BASE_NODE_ID = 65

# BASIC ROUTING
MAX_HOPS = 2

LOG_TO_CONSOLE = False
LOG_TO_FILE = True

BASE_LOG_FILE_NAME = "Network Logs"

# SECONDS
DELAY_INTERVAL = 1500

IS_AUTOMATIC_SIMULATION_ENABLED_BY_DEFAULT = False