GUI_WINDOW_TITLE = "Practical Geographic Forwarding"

GUI_WINDOW_WIDTH = 750
GUI_WINDOW_HEIGHT = 500

SHAPE_RADIUS = 25

MINIMUM_NODE_GENERATION_DISTANCE = SHAPE_RADIUS * 2

MIN_BROADCAST_RANGE = 50
MAX_BROADCAST_RANGE = 150

MIN_CENTROID_MOVEMENT = -25
MAX_CENTROID_MOVEMENT = 25

NUMBER_OF_NODES_TO_GENERATE = 35

# 10%
GUI_CANVAS_CROP_PERCENTAGE = 10

FONT = "Arial 10 bold"

LOCATION_AWARE_NODE_COLOR = "black"
LOCATION_IGNORANT_NODE_COLOR = "green"

NUMBER_OF_MAXIMUM_TRIALS_AT_NODE_GENERATION = 50